In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [11]:
b=np.matrix(l)

In [18]:
type(b)

numpy.matrix

In [12]:
b

matrix([[1, 2, 3, 4]])

In [14]:
e=np.asarray(b)

In [17]:
e

array([[1, 2, 3, 4]])

In [15]:
type(e)

numpy.ndarray

In [16]:
type(b)

numpy.matrix

In [20]:
a=np.array(l)

In [21]:
c=a

In [22]:
c

array([1, 2, 3, 4])

In [23]:
a

array([1, 2, 3, 4])

In [24]:
c[0]=100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [35]:
### a and c are both values are changed bcoz they point to the same memory
### Solo Copy

In [30]:
d=np.copy(a)

In [31]:
d


array([100,   2,   3,   4])

In [32]:
d[0]=50

In [33]:
d

array([50,  2,  3,  4])

In [34]:
a

array([100,   2,   3,   4])

In [36]:
### d copy which will not change the value at origional array

In [37]:
np.fromfunction(lambda i,j : i==j ,(3,3) )

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [46]:
iterable=(i*i for i in range(5))

In [47]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [48]:
iterable

<generator object <genexpr> at 0x0000020ED2828860>

In [50]:
np.fromiter(iterable,int)

array([], dtype=int32)

In [51]:
np.fromstring('123 456',sep=' ')

array([123., 456.])

In [55]:
np.fromstring('123 456 446 456 ' , sep=' ')

array([123., 456., 446., 456.])

In [58]:
np.fromstring("sdf hjk ghy bfg mjk", sep=" ")

C:\Users\vikip\AppData\Local\Temp\ipykernel_10872\1302177928.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("sdf hjk ghy bfg mjk", sep=" ")


array([], dtype=float64)

In [59]:
#Numpy Data types
#

In [60]:
ar=np.array(l)

In [61]:
ar.ndim

1

In [66]:
ar2=np.array([[1,2,3],[4,5,6]])
ar

array([1, 2, 3, 4])

In [67]:
ar2.ndim

2

In [68]:
#ndim will tell us the Diamentions

In [69]:
#size=noof elements

In [70]:
ar.size

4

In [71]:
ar2.size

6

In [72]:
ar.shape

(4,)

In [73]:
ar2.shape

(2, 3)

In [74]:
ar.dtype

dtype('int32')

In [75]:
ar2.dtype

dtype('int32')

In [80]:
ar22=np.array([(1, 3),(23.3,45)])

In [81]:
ar22.dtype

dtype('float64')

In [82]:
list(range(5))

[0, 1, 2, 3, 4]

In [83]:
list(range(1.4,5))

TypeError: 'float' object cannot be interpreted as an integer

In [84]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [85]:
#np.arange(start,end,jump)
np.arange(2.3,5.6, .4)

array([2.3, 2.7, 3.1, 3.5, 3.9, 4.3, 4.7, 5.1, 5.5])

In [86]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [87]:
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [89]:
np.linspace(1,11,10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [93]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [95]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [98]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [99]:
np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [100]:
np.ones((4))

array([1., 1., 1., 1.])

In [102]:
np.ones(4)

array([1., 1., 1., 1.])

In [105]:
on=np.ones((2,4,5))
on

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [109]:
on*5

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [111]:
on+4

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [116]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [118]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.80623720e-321, 3.11525958e-307,
        1.24610723e-306]])

In [119]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [124]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [125]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [126]:
np.logspace(2,4)

array([  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
         145.63484775,   159.98587196,   175.75106249,   193.06977289,
         212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
         308.88435965,   339.32217719,   372.75937203,   409.49150624,
         449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
         655.12855686,   719.685673  ,   790.60432109,   868.51137375,
         954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
        1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
        2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
        2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
        4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
        6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
        9102.98177992, 10000.        ])

In [127]:
np.logspace(2,4,5)

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

In [128]:
np.logspace(0,10,3)

array([1.e+00, 1.e+05, 1.e+10])

In [130]:
arr=np.random.rand(3,4)

In [132]:
import pandas as pd

In [133]:
pd.DataFrame(arr)

0         1         2         3
0  0.640490  0.849577  0.898611  0.305947
1  0.145790  0.002781  0.587505  0.898438
2  0.101153  0.113411  0.372823  0.829236

In [135]:
o=np.zeros((3,4))

In [136]:
o

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
pd.DataFrame(o)

0    1    2    3
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0

In [138]:
np.random.rand(3,4)

array([[0.42450088, 0.20852411, 0.0536219 , 0.61697057],
       [0.42882196, 0.56468664, 0.58095176, 0.03670294],
       [0.59461877, 0.69884554, 0.36777678, 0.67077925]])

In [142]:
np.random.randint(1,100,(4,6))

array([[96, 74, 63,  6, 33, 10],
       [74, 31, 80, 70, 92, 18],
       [19, 57, 53, 90, 83, 88],
       [88, 66, 39, 46, 68, 67]])

In [144]:
pd.DataFrame(np.random.randint(1,110,(300,100))).to_csv('test.csv')
#saves the data to test available