In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [11]:
b=np.matrix(l)

In [18]:
type(b)

numpy.matrix

In [12]:
b

matrix([[1, 2, 3, 4]])

In [14]:
e=np.asarray(b)

In [17]:
e

array([[1, 2, 3, 4]])

In [15]:
type(e)

numpy.ndarray

In [16]:
type(b)

numpy.matrix

In [20]:
a=np.array(l)

In [21]:
c=a

In [22]:
c

array([1, 2, 3, 4])

In [23]:
a

array([1, 2, 3, 4])

In [24]:
c[0]=100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [35]:
### a and c are both values are changed bcoz they point to the same memory
### Solo Copy

In [30]:
d=np.copy(a)

In [31]:
d


array([100,   2,   3,   4])

In [32]:
d[0]=50

In [33]:
d

array([50,  2,  3,  4])

In [34]:
a

array([100,   2,   3,   4])

In [36]:
### d copy which will not change the value at origional array

In [37]:
np.fromfunction(lambda i,j : i==j ,(3,3) )

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])